CREATE TABLE `test`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `age` INT NULL,
  `isAdmin` BIT NOT NULL DEFAULT 0,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

INSERT INTO user (name, age, isAdmin) VALUES('Admin1', 19, 1);
INSERT INTO user (name, age, isAdmin) VALUES('Admin2', 20, 1);
INSERT INTO user (name, age, isAdmin) VALUES('Admin3', 21, 1);
INSERT INTO user (name, age, isAdmin) VALUES('Admin4', 22, 1);
INSERT INTO user (name, age, isAdmin) VALUES('Admin5', 23, 1);
INSERT INTO user (name, age) VALUES('User1', 21);
INSERT INTO user (name, age) VALUES('User2', 21);
INSERT INTO user (name, age) VALUES('User3', 21);
INSERT INTO user (name, age) VALUES('User4', 21);
INSERT INTO user (name, age) VALUES('User5', 21);
INSERT INTO user (name, age) VALUES('User6', 21);
INSERT INTO user (name, age) VALUES('User7', 21);
INSERT INTO user (name, age) VALUES('User8', 21);
INSERT INTO user (name, age) VALUES('User1', 22);
INSERT INTO user (name, age) VALUES('User2', 22);
INSERT INTO user (name, age) VALUES('User3', 22);
INSERT INTO user (name, age) VALUES('User4', 22);
INSERT INTO user (name, age) VALUES('User5', 22);
INSERT INTO user (name, age) VALUES('User6', 22);
INSERT INTO user (name, age) VALUES('User7', 22);
INSERT INTO user (name, age) VALUES('User8', 22);
INSERT INTO user (name, age) VALUES('User1', 23);
INSERT INTO user (name, age) VALUES('User2', 23);
INSERT INTO user (name, age) VALUES('User3', 23);
INSERT INTO user (name, age) VALUES('User4', 23);
INSERT INTO user (name, age) VALUES('User5', 23);
INSERT INTO user (name, age) VALUES('User6', 23);
INSERT INTO user (name, age) VALUES('User7', 23);
INSERT INTO user (name, age) VALUES('User8', 23);
INSERT INTO user (name, age) VALUES('User1', 24);
INSERT INTO user (name, age) VALUES('User2', 24);
INSERT INTO user (name, age) VALUES('User3', 24);
INSERT INTO user (name, age) VALUES('User4', 24);
INSERT INTO user (name, age) VALUES('User5', 24);
INSERT INTO user (name, age) VALUES('User6', 24);
INSERT INTO user (name, age) VALUES('User7', 24);
INSERT INTO user (name, age) VALUES('User8', 24);
INSERT INTO user (name, age) VALUES('User1', 25);
INSERT INTO user (name, age) VALUES('User2', 25);
INSERT INTO user (name, age) VALUES('User3', 25);
INSERT INTO user (name, age) VALUES('User4', 25);
INSERT INTO user (name, age) VALUES('User5', 25);
INSERT INTO user (name, age) VALUES('User6', 25);
INSERT INTO user (name, age) VALUES('User7', 25);
INSERT INTO user (name, age) VALUES('User8', 25);
INSERT INTO user (name, age) VALUES('User1', 26);
INSERT INTO user (name, age) VALUES('User2', 26);
INSERT INTO user (name, age) VALUES('User3', 26);
INSERT INTO user (name, age) VALUES('User4', 26);
INSERT INTO user (name, age) VALUES('User5', 26);
INSERT INTO user (name, age) VALUES('User6', 26);
INSERT INTO user (name, age) VALUES('User7', 26);
INSERT INTO user (name, age) VALUES('User8', 26);
INSERT INTO user (name, age) VALUES('User1', 27);
INSERT INTO user (name, age) VALUES('User2', 27);
INSERT INTO user (name, age) VALUES('User3', 27);
INSERT INTO user (name, age) VALUES('User4', 27);
INSERT INTO user (name, age) VALUES('User5', 27);
INSERT INTO user (name, age) VALUES('User6', 27);
INSERT INTO user (name, age) VALUES('User7', 27);
INSERT INTO user (name, age) VALUES('User8', 27);
INSERT INTO user (name, age) VALUES('User1', 28);
INSERT INTO user (name, age) VALUES('User2', 28);
INSERT INTO user (name, age) VALUES('User3', 28);
INSERT INTO user (name, age) VALUES('User4', 28);
INSERT INTO user (name, age) VALUES('User5', 28);
INSERT INTO user (name, age) VALUES('User6', 28);
INSERT INTO user (name, age) VALUES('User7', 28);
INSERT INTO user (name, age) VALUES('User8', 28);
INSERT INTO user (name, age) VALUES('User1', 29);
INSERT INTO user (name, age) VALUES('User2', 29);
INSERT INTO user (name, age) VALUES('User3', 29);
INSERT INTO user (name, age) VALUES('User4', 29);
INSERT INTO user (name, age) VALUES('User5', 29);
INSERT INTO user (name, age) VALUES('User6', 29);
INSERT INTO user (name, age) VALUES('User7', 29);
INSERT INTO user (name, age) VALUES('User8', 29);
INSERT INTO user (name, age) VALUES('User1', 30);
INSERT INTO user (name, age) VALUES('User2', 30);
INSERT INTO user (name, age) VALUES('User3', 30);
INSERT INTO user (name, age) VALUES('User4', 30);
INSERT INTO user (name, age) VALUES('User5', 30);
INSERT INTO user (name, age) VALUES('User6', 30);
INSERT INTO user (name, age) VALUES('User7', 30);
INSERT INTO user (name, age) VALUES('User8', 30);